apiVersion: v1
kind: Service
metadata:
  name: eks-asap-api-linux-service
  namespace: eks-asap-api-app
  labels:
    app: eks-asap-api-linux-app
spec:
  selector:
    app: eks-asap-api-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
